/* 知识库条目 · 增删卜易 第十批（用神章 L543，元神的日月动爻生扶）
   ────────────────────────────────────────────────────────────────────────
   元神旺相，或临日月，或得日月动爻生扶者，一也。
   → state:L<p>:元·日月动爻生扶  (the 元神 is generated by the day or the month)
   Verbatim, checked by tests/kb-entries.mjs. Only with a 用神 given (the 元神 is defined by it).
*/

const BOOK = '增删卜易';
const POS = [1, 2, 3, 4, 5, 6];

export const ZENGBU_BATCH10 = POS.map((p) => ({
  id: `zb-l543-yuan-riyue-p${p}`,
  source: { book: BOOK, chapter: '卷二 · 用神章', license: 'public-domain', line: 'L543' },
  text_zh: '得日月动爻生扶',
  when: [`state:L${p}:元·日月动爻生扶`]
}));
