/* GENERATED by scripts/build-relative-gloss.mjs — do not edit by hand.
   Source: assets/xiangshu/lei-xiang.json (the catalogue is the only owner of
   these words). Regenerate after editing either the catalogue or the route map,
   and tests/relative-gloss.mjs will fail if this file has drifted from them.

   What this is for: a 六亲 means one thing and denotes many. This carries the
   many, indexed by what was asked, so the reading can name the real thing
   instead of printing the label. */
export const RELATIVE_FACETS = {
  "父母": {
    "en": "Resource",
    "cats": {
      "文书": {
        "en": "paperwork",
        "zh": [
          "合同",
          "证书",
          "执照",
          "资质",
          "批文",
          "备案"
        ],
        "items_en": [
          "a contract",
          "a certificate",
          "a licence",
          "a qualification",
          "an approval",
          "a filing"
        ]
      },
      "房产": {
        "en": "property",
        "zh": [
          "房子",
          "土地",
          "办公室",
          "店面",
          "仓库",
          "租约"
        ],
        "items_en": [
          "a house",
          "land",
          "an office",
          "a shopfront",
          "a warehouse",
          "a lease"
        ]
      },
      "长辈": {
        "en": "elders",
        "zh": [
          "父母",
          "老师",
          "师父",
          "上级、主管",
          "出资人",
          "监护人"
        ],
        "items_en": [
          "parents",
          "a teacher",
          "a mentor",
          "a boss or supervisor",
          "whoever put up the money",
          "a guardian"
        ]
      },
      "车船": {
        "en": "what carries you",
        "zh": [
          "车",
          "船",
          "飞机",
          "通勤的路",
          "行李、行装",
          "搬运的工具"
        ],
        "items_en": [
          "a car",
          "a boat",
          "a plane",
          "the commute itself",
          "luggage, kit",
          "whatever moves things for you"
        ]
      },
      "平台": {
        "en": "the thing you sit on",
        "zh": [
          "平台规则",
          "上级单位",
          "主管机关",
          "渠道方的条款",
          "你挂靠的那套体系",
          "服务器、基础设施"
        ],
        "items_en": [
          "platform rules",
          "the parent organisation",
          "a regulator",
          "a channel's terms",
          "the system you operate under",
          "servers, infrastructure"
        ]
      },
      "学业": {
        "en": "study and word-of-mouth",
        "zh": [
          "学历",
          "课程、培训",
          "考试",
          "论文",
          "消息、通知",
          "口碑、名声传出去的那部分"
        ],
        "items_en": [
          "a degree",
          "courses, training",
          "an examination",
          "a thesis",
          "news, an announcement",
          "word getting around about you"
        ]
      },
      "操劳": {
        "en": "the toil",
        "zh": [
          "亲手做的活",
          "跑腿、办手续",
          "加班",
          "照顾人",
          "反复返工的那一摊"
        ],
        "items_en": [
          "work done by hand",
          "errands, paperwork queues",
          "overtime",
          "caring for someone",
          "the part you keep redoing"
        ]
      },
      "遮盖": {
        "en": "what covers you",
        "zh": [
          "衣服",
          "伞",
          "屋顶",
          "围墙",
          "保险",
          "挡风的那层东西"
        ],
        "items_en": [
          "clothing",
          "an umbrella",
          "a roof",
          "a wall",
          "insurance",
          "whatever keeps the weather off"
        ]
      },
      "根基": {
        "en": "the footing",
        "zh": [
          "地基",
          "本钱",
          "家底",
          "学过的东西",
          "撑住你的那一层"
        ],
        "items_en": [
          "foundations",
          "starting capital",
          "what the family has",
          "what you were taught",
          "the layer holding you up"
        ]
      }
    }
  },
  "兄弟": {
    "en": "Peer",
    "cats": {
      "同辈": {
        "en": "peers",
        "zh": [
          "兄弟姐妹",
          "同学",
          "同事",
          "同龄的朋友",
          "同门"
        ],
        "items_en": [
          "siblings",
          "classmates",
          "colleagues",
          "friends your own age",
          "people from the same training"
        ]
      },
      "同行": {
        "en": "rivals",
        "zh": [
          "竞品",
          "同赛道的人",
          "抢同一批客户的",
          "模仿你的人",
          "比价的对手"
        ],
        "items_en": [
          "a competing product",
          "others in the same lane",
          "whoever wants the same customers",
          "imitators",
          "whoever you get priced against"
        ]
      },
      "分利的": {
        "en": "whoever splits it",
        "zh": [
          "合伙人",
          "股东",
          "中介、代理",
          "抽成的渠道",
          "分销商",
          "要分红的人"
        ],
        "items_en": [
          "a partner",
          "a shareholder",
          "a broker or agent",
          "a channel taking a cut",
          "a distributor",
          "anyone owed a share"
        ]
      },
      "耗费": {
        "en": "what eats it",
        "zh": [
          "成本",
          "手续费、平台抽成",
          "房租",
          "人工",
          "被浪费掉的时间",
          "被分走的精力"
        ],
        "items_en": [
          "costs",
          "fees and platform cuts",
          "rent",
          "wages",
          "time wasted",
          "attention pulled away"
        ]
      },
      "争夺": {
        "en": "contention",
        "zh": [
          "争执、吵架",
          "议价",
          "抢单",
          "口舌是非",
          "僵持不下的那件事"
        ],
        "items_en": [
          "an argument",
          "haggling",
          "fighting for the same deal",
          "gossip and friction",
          "the thing that has stalled in a standoff"
        ]
      },
      "阻隔": {
        "en": "what stands in the way",
        "zh": [
          "门、墙",
          "中间那道关",
          "挡在中间的人",
          "难跨的那一步"
        ],
        "items_en": [
          "a door, a wall",
          "the gate in the middle",
          "whoever stands between",
          "the step that is hard to get over"
        ]
      },
      "邻里": {
        "en": "those alongside",
        "zh": [
          "邻居",
          "同乡",
          "同一栋楼的人",
          "常打交道的外人"
        ],
        "items_en": [
          "neighbours",
          "people from home",
          "whoever shares the building",
          "the outsiders you deal with daily"
        ]
      },
      "风声": {
        "en": "what blows through",
        "zh": [
          "风",
          "传言",
          "一阵一阵的热度",
          "来去不定的东西"
        ],
        "items_en": [
          "wind",
          "rumour",
          "a fad that comes in waves",
          "what arrives and leaves"
        ]
      }
    }
  },
  "子孙": {
    "en": "Output",
    "cats": {
      "出品": {
        "en": "what you make",
        "zh": [
          "产品",
          "作品",
          "服务",
          "课程",
          "内容",
          "一门手艺做出来的东西"
        ],
        "items_en": [
          "a product",
          "a piece of work",
          "a service",
          "a course",
          "content",
          "whatever the craft turns out"
        ]
      },
      "晚辈": {
        "en": "juniors",
        "zh": [
          "子女",
          "学生",
          "徒弟",
          "下属",
          "带的新人"
        ],
        "items_en": [
          "children",
          "students",
          "apprentices",
          "subordinates",
          "the newcomer you are training"
        ]
      },
      "解厄": {
        "en": "what relieves it",
        "zh": [
          "医药",
          "治疗",
          "休息",
          "保险",
          "化解的办法",
          "那个能替你挡一下的东西"
        ],
        "items_en": [
          "medicine",
          "treatment",
          "rest",
          "insurance",
          "the way out of it",
          "whatever takes the hit for you"
        ]
      },
      "财源": {
        "en": "where money comes from",
        "zh": [
          "复购的客户",
          "持续的收入",
          "被动收入",
          "口碑带来的单",
          "能自己转起来的那部分"
        ],
        "items_en": [
          "repeat customers",
          "recurring income",
          "income that arrives without you",
          "work that arrives by reputation",
          "the part that runs itself"
        ]
      },
      "技术": {
        "en": "craft",
        "zh": [
          "手艺",
          "方法、诀窍",
          "工具",
          "专利",
          "积累下来的能力"
        ],
        "items_en": [
          "a skill",
          "a method, a knack",
          "tools",
          "a patent",
          "capability you have built up"
        ]
      },
      "欢喜": {
        "en": "ease",
        "zh": [
          "快乐",
          "放松",
          "玩、休闲",
          "宠物",
          "让你不紧绷的那件事"
        ],
        "items_en": [
          "gladness",
          "letting go",
          "play, leisure",
          "a pet",
          "whatever loosens you"
        ]
      },
      "信仰": {
        "en": "what you lean on",
        "zh": [
          "僧道",
          "信念",
          "修行",
          "让你安心的那套说法"
        ],
        "items_en": [
          "clergy",
          "conviction",
          "practice",
          "the account of things that settles you"
        ]
      },
      "六畜": {
        "en": "the animals",
        "zh": [
          "牲口",
          "宠物",
          "养的东西"
        ],
        "items_en": [
          "livestock",
          "a pet",
          "whatever you keep and feed"
        ]
      }
    }
  },
  "妻财": {
    "en": "Wealth",
    "cats": {
      "钱": {
        "en": "money",
        "zh": [
          "现金",
          "收入",
          "利润",
          "工资",
          "分红",
          "回款"
        ],
        "items_en": [
          "cash",
          "income",
          "profit",
          "salary",
          "a dividend",
          "money coming back in"
        ]
      },
      "货": {
        "en": "goods",
        "zh": [
          "商品",
          "库存",
          "原料",
          "设备",
          "要卖的东西"
        ],
        "items_en": [
          "merchandise",
          "stock",
          "materials",
          "equipment",
          "whatever is for sale"
        ]
      },
      "产业": {
        "en": "holdings",
        "zh": [
          "店",
          "公司股份",
          "投资",
          "收租的东西",
          "账户"
        ],
        "items_en": [
          "a shop",
          "a stake in a company",
          "investments",
          "whatever pays you rent",
          "an account"
        ]
      },
      "女方": {
        "en": "the woman (for a man)",
        "zh": [
          "妻子",
          "女友",
          "相亲对象",
          "前任"
        ],
        "items_en": [
          "a wife",
          "a girlfriend",
          "someone being introduced",
          "an ex"
        ]
      },
      "人手": {
        "en": "the hands",
        "zh": [
          "员工",
          "帮工",
          "外包",
          "替你做事的人"
        ],
        "items_en": [
          "employees",
          "helpers",
          "contractors",
          "whoever does it for you"
        ]
      },
      "器物": {
        "en": "things",
        "zh": [
          "器皿、家什",
          "仓库",
          "日用的东西",
          "被你占着的那些物件"
        ],
        "items_en": [
          "utensils and furnishings",
          "storage",
          "daily objects",
          "the things you keep"
        ]
      },
      "食禄": {
        "en": "what feeds you",
        "zh": [
          "饭食",
          "酒",
          "日常开销",
          "养活你的那份"
        ],
        "items_en": [
          "food",
          "drink",
          "daily spending",
          "the part that keeps you fed"
        ]
      },
      "凭据": {
        "en": "proof of it",
        "zh": [
          "账",
          "流水",
          "合约上的数",
          "看得见的凭证"
        ],
        "items_en": [
          "the accounts",
          "the ledger",
          "the number on the contract",
          "evidence you can point to"
        ]
      }
    }
  },
  "官鬼": {
    "en": "Pressure",
    "cats": {
      "职务": {
        "en": "the post",
        "zh": [
          "工作",
          "职位",
          "职称",
          "编制",
          "头衔",
          "那个位子"
        ],
        "items_en": [
          "a job",
          "a position",
          "a rank",
          "a permanent post",
          "a title",
          "the seat itself"
        ]
      },
      "上头": {
        "en": "authority",
        "zh": [
          "上司",
          "甲方",
          "监管",
          "审批那一关",
          "评审、评委",
          "执法的人"
        ],
        "items_en": [
          "a boss",
          "the client who decides",
          "a regulator",
          "the approval step",
          "a review panel",
          "whoever enforces"
        ]
      },
      "男方": {
        "en": "the man (for a woman)",
        "zh": [
          "丈夫",
          "男友",
          "追求者",
          "前任"
        ],
        "items_en": [
          "a husband",
          "a boyfriend",
          "someone pursuing her",
          "an ex"
        ]
      },
      "病": {
        "en": "illness",
        "zh": [
          "病症",
          "旧疾",
          "伤",
          "查出来的问题"
        ],
        "items_en": [
          "a complaint",
          "something long-standing",
          "an injury",
          "what a check turned up"
        ]
      },
      "讼": {
        "en": "disputes",
        "zh": [
          "官司",
          "纠纷",
          "投诉",
          "索赔",
          "被追责的事"
        ],
        "items_en": [
          "a lawsuit",
          "a dispute",
          "a complaint",
          "a claim",
          "being held to account"
        ]
      },
      "压": {
        "en": "what presses",
        "zh": [
          "竞争压力",
          "责任",
          "期限",
          "风险",
          "不敢想的那件事",
          "躲不过去的那一关"
        ],
        "items_en": [
          "competitive pressure",
          "responsibility",
          "a deadline",
          "risk",
          "the thing you avoid thinking about",
          "the step you cannot go around"
        ]
      },
      "意外": {
        "en": "what comes at you",
        "zh": [
          "盗窃",
          "失窃、丢东西",
          "突发的事",
          "被算计"
        ],
        "items_en": [
          "theft",
          "losing something",
          "something sudden",
          "being played"
        ]
      },
      "功名": {
        "en": "standing",
        "zh": [
          "名分",
          "资历",
          "评级",
          "被承认的那一层"
        ],
        "items_en": [
          "a title",
          "seniority",
          "a rating",
          "the recognition itself"
        ]
      },
      "心魔": {
        "en": "what haunts",
        "zh": [
          "鬼神",
          "梦魇",
          "放不下的事",
          "半夜想起来的那件"
        ],
        "items_en": [
          "spirits",
          "a nightmare",
          "what will not be put down",
          "the thing that wakes you"
        ]
      },
      "天灾": {
        "en": "what falls on you",
        "zh": [
          "雷电",
          "风雨",
          "停电、断网",
          "轮不到你决定的坏事"
        ],
        "items_en": [
          "thunder",
          "storms",
          "an outage",
          "the bad thing you did not choose"
        ]
      }
    }
  }
};

export const ROUTE_FACETS = {
  "relationship": {
    "兄弟": [
      "争夺",
      "阻隔",
      "同辈",
      "同行"
    ],
    "妻财": [
      "女方",
      "钱"
    ],
    "官鬼": [
      "男方",
      "心魔",
      "压",
      "讼"
    ],
    "父母": [
      "长辈",
      "遮盖",
      "根基"
    ],
    "子孙": [
      "欢喜",
      "解厄"
    ]
  },
  "intimacy": {
    "兄弟": [
      "争夺",
      "阻隔",
      "同行"
    ],
    "妻财": [
      "女方"
    ],
    "官鬼": [
      "男方",
      "心魔",
      "压",
      "病"
    ],
    "父母": [
      "长辈",
      "遮盖"
    ],
    "子孙": [
      "欢喜",
      "解厄"
    ]
  },
  "wealth": {
    "兄弟": [
      "分利的",
      "耗费",
      "同行",
      "争夺"
    ],
    "妻财": [
      "钱",
      "货",
      "产业",
      "食禄",
      "凭据"
    ],
    "官鬼": [
      "职务",
      "上头",
      "讼",
      "压",
      "功名"
    ],
    "父母": [
      "文书",
      "平台",
      "根基",
      "车船",
      "操劳"
    ],
    "子孙": [
      "财源",
      "出品",
      "技术",
      "解厄"
    ]
  },
  "appearance": {
    "兄弟": [
      "同辈",
      "邻里"
    ],
    "妻财": [
      "女方",
      "器物",
      "货"
    ],
    "官鬼": [
      "男方",
      "功名",
      "病"
    ],
    "父母": [
      "长辈",
      "遮盖",
      "车船"
    ],
    "子孙": [
      "出品",
      "技术",
      "六畜"
    ]
  },
  "future_unseen": {
    "兄弟": [
      "同辈",
      "同行"
    ],
    "妻财": [
      "女方",
      "钱"
    ],
    "官鬼": [
      "男方",
      "功名",
      "职务"
    ],
    "父母": [
      "长辈",
      "根基",
      "学业"
    ],
    "子孙": [
      "晚辈",
      "欢喜",
      "出品"
    ]
  },
  "timing": {},
  "choice": {},
  "general": {}
};

/* Candidates for the relatives that are actually on this board, under this
   route. Returns [] when nothing applies, so the caller can leave the section
   out entirely rather than injecting an empty heading. */
export function relativeGloss(relativesOnBoard, route, lang) {
  const zh = lang === 'zh';
  const pref = ROUTE_FACETS[route] || {};
  const out = [];
  for (const rel of ["父母","兄弟","子孙","妻财","官鬼"]) {
    if (relativesOnBoard && relativesOnBoard.indexOf(rel) < 0) continue;
    const entry = RELATIVE_FACETS[rel];
    if (!entry) continue;
    const names = (pref[rel] && pref[rel].length) ? pref[rel] : Object.keys(entry.cats);
    const lines = [];
    for (const name of names) {
      const c = entry.cats[name];
      if (!c) continue;
      const items = zh ? c.zh : (c.items_en.length ? c.items_en : c.zh);
      if (!items.length) continue;
      lines.push((zh ? name : c.en) + ': ' + items.join('、'));
    }
    if (lines.length) out.push((zh ? rel : rel + ' (' + entry.en + ')') + ' — ' + lines.join(' | '));
  }
  return out;
}
