/* 增删卜易 章目覆盖表 — every chapter of the book has one row here.
   ────────────────────────────────────────────────────────────────────────
   status:
     packet         the program computes it; `where` names the packet fields
     packet+model   the program computes the facts; the model judges the rest
     model          a judgment or a 门类 rule. It goes into the knowledge base
                    (step 5, not yet built) and the model reads it from there
     casting        起卦 itself, still to be moved to the server (step 3)
     excluded       the book itself rejects it; quoted in `note`
   tests/kb-coverage.mjs checks that the chapter list below is the book's, that
   every chapter has exactly one row, and that every `where` path exists.
*/
export const COVERAGE = [
  ["八卦章", { status: "packet", where: ["ben.upper", "ben.lower", "ben.palace"], note: "" }],
  ["占卦法章", { status: "casting", where: ["ben.bits", "moving"], note: "起卦在服务端，尚未做；packet 只接收结果。" }],
  ["八宫章", { status: "packet", where: ["ben.name", "ben.palace", "ben.series"], note: "" }],
  ["浑天甲子章", { status: "packet", where: ["lines[].stem", "lines[].branch"], note: "" }],
  ["六亲歌章", { status: "packet", where: ["lines[].relative"], note: "" }],
  ["世应章", { status: "packet", where: ["ben.world", "ben.ying"], note: "" }],
  ["动变章", { status: "packet", where: ["bian.name", "bian.bits", "moving", "lines[].transform.branch", "lines[].transform.relative"], note: "" }],
  ["用神章", { status: "packet+model", where: ["yong.key", "yong.lines"], note: "哪一六亲对应哪一事，由模型据用神章判断。" }],
  ["用神、元神、忌神、仇神章", { status: "packet", where: ["yong.yuan.lines", "yong.ji.lines", "yong.chou.lines"], note: "" }],
  ["元神、忌神、衰旺章", { status: "packet+model", where: ["yong.yuan.factors[].factors"], note: "五条有力之条由程序给出；“有力”的判断由模型据章文定。" }],
  ["五行相生章", { status: "packet", where: ["relations.elements[].rel"], note: "" }],
  ["五行相克章", { status: "packet", where: ["relations.elements[].rel"], note: "" }],
  ["克处逢生章", { status: "packet+model", where: ["relations.elements[].rel"], note: "五行关系由程序给出；如何断由模型据章文判定。" }],
  ["动静生克章", { status: "packet", where: ["relations.elements[].moving", "relations.chong[].moving"], note: "" }],
  ["动变生克冲合章", { status: "packet", where: ["lines[].transform.backToSheng", "lines[].transform.backToKe", "lines[].transform.clashBen", "lines[].transform.combineBen"], note: "" }],
  ["四时旺相章", { status: "packet", where: ["lines[].wangShuai.rank", "lines[].monthRank"], note: "" }],
  ["月将章", { status: "packet", where: ["lines[].toMonth", "lines[].monthBreak", "lines[].monthCombine"], note: "" }],
  ["日辰章", { status: "packet", where: ["lines[].toDay", "lines[].dayClash", "lines[].dayCombine", "relations.dayEffects[].pos"], note: "" }],
  ["六神章", { status: "packet", where: ["lines[].spirit"], note: "" }],
  ["六合章", { status: "packet", where: ["hexFlags.combine", "relations.he[].type", "lines[].heKinds", "hexFlags.transitions"], note: "" }],
  ["三合章", { status: "packet", where: ["relations.sanhe[].parts[][].from"], note: "" }],
  ["六冲章", { status: "packet", where: ["hexFlags.clash", "relations.chong[].moving", "lines[].chongKinds", "hexFlags.transitions"], note: "" }],
  ["三刑章", { status: "packet", where: ["relations.xing[].from", "relations.xing[].self"], note: "" }],
  ["六害章", { status: "excluded", where: [], note: "书云：“六害全无应验，删之不录。”不计算。" }],
  ["暗动章", { status: "packet", where: ["relations.dayEffects[].effects"], note: "" }],
  ["动散章", { status: "packet+model", where: ["relations.dayEffects[].effects"], note: "动散候选由程序给出；旺相、有气不散的例外由模型据章文判断。" }],
  ["卦变生克墓绝章", { status: "packet+model", where: ["bian.bianVsBen"], note: "变卦宫与本卦宫的生克由程序给出；变墓、变绝由模型据章文判断。" }],
  ["反伏章", { status: "packet+model", where: ["hexFlags.trigramFanYin", "hexFlags.fuYin", "lines[].fuYin", "lines[].fanYin"], note: "反吟、伏吟的机械条件由程序给出；其占断意义由模型据章文判断。" }],
  ["旬空章", { status: "packet", where: ["lines[].void", "lines[].voidVerdict", "lines[].trueVoid", "time.xunkong"], note: "" }],
  ["生旺墓绝章", { status: "packet", where: ["lines[].dayStage", "lines[].changeStage"], note: "" }],
  ["各门类题头总注章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["各门类应期总注章", { status: "packet+model", where: ["lines[].dayStage", "lines[].heKinds", "lines[].chongKinds"], note: "应期的时间结论由模型据章文判断；动静值合冲的事实由程序给出。" }],
  ["归魂游魂章", { status: "packet+model", where: ["ben.series"], note: "系列由程序给出；断语意义入知识库。" }],
  ["月破章", { status: "packet", where: ["lines[].monthBreak"], note: "" }],
  ["飞伏神章", { status: "packet", where: ["lines[].hidden", "yong.fallback.palaceFirst.lines"], note: "" }],
  ["进神退神章", { status: "packet", where: ["lines[].transform.jinTui"], note: "" }],
  ["随鬼入墓章", { status: "packet", where: ["lines[].tombs.day", "lines[].tombs.moving", "lines[].tombs.change"], note: "卦身、世身、本命不取（书明言），见“书中明言不取”。" }],
  ["独发章", { status: "packet", where: ["solo"], note: "" }],
  ["两现章", { status: "packet", where: ["yong.liangXian"], note: "" }],
  ["星煞章", { status: "packet", where: ["shensha.taiyi", "shensha.lu", "shensha.yima", "shensha.tianxi"], note: "书只验此四种，其余不取。" }],
  ["天时章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["身命章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["终身财福章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["终身功吊有无章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["终身功名有无章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["寿元章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["趋避章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["父母寿元章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["兄弟章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["夫妇章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["子嗣章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["学业章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["治经章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["延师章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["求吊章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["求名章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["童试章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["岁考科考章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["占廪章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["发案挂榜章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["乡试会试章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["升选候补章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["升迁何方章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["在任吉凶章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["投麾效用，入武从军章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["署印谋差章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["防参劾、虑大计、及已有事尚未结案者章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["养亲、告病、辞官章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["修陵修河，一切营造公务防患章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["僧官、道纪、医官、杂职、阴阳等官章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["功吊到何品级章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["功名到何品级章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["子占父功吊章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["子占父功名章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["求财章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["谒贵求财章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["为贵人奔走效力求财章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["开行开店及各项铺面章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["投行损益章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["囤货卖货章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["卖货宜守宜动章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["往何方买卖章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["买何货为吉章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["借贷章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["放债索债章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["买卖六畜章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["博戏章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["请会摇会章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["行险求财章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["婚姻章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["此婚子嗣有无章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["此婚有宜于父母否章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["纳宠章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["配仆章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["取离妇跳娼妇章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["胎孕章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["产妇安危章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["产期章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["婴儿否泰章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["出行章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["舟行章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["同舟共行章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["行人章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["防非避讼章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["斗殴争竞章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["兴词举讼章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["已定重罪章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["疾病章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["痘疹章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["病源章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["鬼神章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["延医章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["医占往治章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["家宅章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["盖造、买宅、赁宅章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["创造宫室章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["修方动土章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["迁居过火章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["归宅入火章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["入宅六亲吉凶章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["马房猪圈章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["旧宅章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["同居章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["盖造官衙章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["衙宇章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["盖造寺院章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["莹葬章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["寻地章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["占地形势章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["得地于何时章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["得地于何方章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["占地师章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["点穴章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["谋地偷葬章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["祖莹旧冢章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["因何事所伤章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["修补秘法章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["再占修补吉凶章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
  ["新亡附葬祖墓章", { status: "model", where: [], note: "门类断法或占事判断，入知识库，由模型依章文使用。" }],
];
