/**
 * CASTING PACKET CONTRACT
 *
 * The 卦况包 is the program's complete account of a casting, and every later
 * model stage reads from it. Three things here must hold, or the reading built
 * on top of it is wrong from the start:
 *
 *   1. THE HEXAGRAM NAMES ARE THE BOOK'S. The 64 names are checked against the
 *      八宫卦吊 list in 增删卜易 (the list below is copied from the source, not
 *      generated by the code under test). A name that differs from the book
 *      would make the knowledge base index on the wrong hexagram.
 *
 *   2. 进退 FOLLOWS THE BOOK'S TABLE. 进神退神章 lists eight advancing and eight
 *      retreating pairs. The engine's own jinTui carries only four of each, so
 *      it silently reports 丑辰未戌 moves as "no 进退". The packet must match
 *      the book. The engine gap is recorded, not hidden: see the last block.
 *
 *   3. THE PACKET AND THE MATCHER AGREE. `packet.tokens` must equal what the
 *      feature extractor emits, so a reading can never cite a fact the
 *      retrieval stage cannot see, or the reverse.
 *
 * Run: node tests/kb-packet.mjs
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import vm from 'node:vm';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const KB = resolve(ROOT, 'src');

const sandbox = { window: {}, console, Date };
sandbox.window.window = sandbox.window;
vm.createContext(sandbox);
vm.runInContext(readFileSync(resolve(ROOT, 'vendor/liuyao-engine.js'), 'utf8'), sandbox, { filename: 'vendor/liuyao-engine.js' });
const BWLiuYao = sandbox.window.BWLiuYao;

const { buildPacket, jinTuiOf, nameOfBits } = await import(pathToFileURL(resolve(KB, 'packet.js')).href);
const { factTokens } = await import(pathToFileURL(resolve(KB, 'facts.js')).href);
const { boardFeatures } = await import(pathToFileURL(resolve(KB, 'features.js')).href);

const DATE = new Date(2026, 9, 8, 10, 0);
// "初爻 first" string → the integer the engine takes. Bit i is line i+1.
const bitsOf = (s) => parseInt([...s].reverse().join(''), 2);

function boardFor(bits, moving, date = DATE) {
  const lines = [0, 1, 2, 3, 4, 5].map((i) => ({ yang: !!((bits >> i) & 1), changing: false }));
  return BWLiuYao.computeBoard({ lines, changeIdx: moving, date });
}

/* 八宫卦吊, 增删卜易 卷一 (copied from the book, palace by palace). Index is
   the palace order the book prints: 乾 坎 艮 震 巽 离 坤 兑. */
const BOOK_NAMES = [
  '乾为天', '天风姤', '天山遁', '天地否', '风地观', '山地剥', '火地晋', '火天大有',
  '坎为水', '水泽节', '水雷屯', '水火既济', '泽火革', '雷火丰', '地火明夷', '地水师',
  '艮为山', '山火贲', '山天大畜', '山泽损', '火泽睽', '天泽履', '风泽中孚', '风山渐',
  '震为雷', '雷地豫', '雷水解', '雷风恒', '地风升', '水风井', '泽风大过', '泽雷随',
  '巽为风', '风天小畜', '风火家人', '风雷益', '天雷无妄', '火雷噬嗑', '山雷颐', '山风蛊',
  '离为火', '火山旅', '火风鼎', '火水未济', '山水蒙', '风水涣', '天水讼', '天火同人',
  '坤为地', '地雷复', '地泽临', '地天泰', '雷天大壮', '泽天夬', '水天需', '水地比',
  '兑为泽', '泽水困', '泽地萃', '泽山咸', '水山蹇', '地山谦', '雷山小过', '雷泽归妹'
];

let NAME_OF = null; // bits → name, filled by section 1, reused by section 3

// 1. Names. Build every bit pattern, read the name the packet gives it, and
//    compare the whole set to the book's list.
{
  assert.equal(new Set(BOOK_NAMES).size, 64, 'the copied book list must itself have 64 distinct names');
  const got = new Map();
  for (let bits = 0; bits < 64; bits++) {
    const p = buildPacket(boardFor(bits, []));
    got.set(bits, p.ben.name);
  }
  NAME_OF = got;
  const names = [...got.values()];
  assert.equal(new Set(names).size, 64, 'the packet gives two hexagrams the same name');
  assert.deepEqual([...new Set(names)].sort(), [...new Set(BOOK_NAMES)].sort(),
    'the packet names differ from the 八宫卦吊 list');

  // Independent cross-check, not using the packet's tables: the name must open
  // with the nature word of its own upper trigram and close its 下卦 with the
  // nature word of its lower trigram. Trigram order is bit 0 = bottom line.
  const TRI_NATURE = ['地', '雷', '水', '泽', '山', '火', '风', '天']; // tb 0..7
  for (let bits = 0; bits < 64; bits++) {
    const name = got.get(bits);
    const lower = bits & 7, upper = (bits >> 3) & 7;
    if (upper === lower) {
      assert.equal(name, `${['坤', '震', '坎', '兑', '艮', '离', '巽', '乾'][upper]}为${TRI_NATURE[upper]}`,
        `pure hexagram ${bits} must read X为X`);
    } else {
      assert.equal(name.slice(0, 2), TRI_NATURE[upper] + TRI_NATURE[lower],
        `${name} (bits ${bits}): upper ${TRI_NATURE[upper]} / lower ${TRI_NATURE[lower]} must open the name`);
    }
  }
  // The lookup and the packet agree.
  for (let bits = 0; bits < 64; bits++) assert.equal(nameOfBits(bits), got.get(bits));

  // Spot checks where the book's own text fixes the answer. 水火既济 is
  // 101010 from the bottom line up (the 占卦法章 example).
  assert.equal(got.get(bitsOf('101010')), '水火既济', '101010 must be 水火既济');
  assert.equal(got.get(bitsOf('010101')), '火水未济', '010101 must be 火水未济');
  assert.equal(got.get(bitsOf('111111')), '乾为天', '111111 must be 乾为天');
  assert.equal(got.get(bitsOf('000000')), '坤为地', '000000 must be 坤为地');
}

// 2. 进退. The book's sixteen pairs, each checked both ways, and the non-pairs.
{
  const ADV = [['亥', '子'], ['寅', '卯'], ['巳', '午'], ['申', '酉'],
    ['丑', '辰'], ['辰', '未'], ['未', '戌'], ['戌', '丑']];
  const RET = [['子', '亥'], ['卯', '寅'], ['午', '巳'], ['酉', '申'],
    ['辰', '丑'], ['未', '辰'], ['戌', '未'], ['丑', '戌']];
  for (const [a, b] of ADV) assert.equal(jinTuiOf(a, b), '进神', `${a}化${b} is 进神 in 进神退神章`);
  for (const [a, b] of RET) assert.equal(jinTuiOf(a, b), '退神', `${a}化${b} is 退神 in 进神退神章`);
  assert.equal(jinTuiOf('子', '丑'), null, 'a non-pair is neither');
  assert.equal(jinTuiOf('寅', '亥'), null, 'reversing an advance is not a retreat');
}

// 3. A moving board: the packet's facts and the feature tokens line up.
{
  const bits = bitsOf('101010');  // 水火既济, from the bottom line up
  const moving = [2, 3, 4];       // 第三、四、五爻动 (1-based 3,4,5)
  const board = boardFor(bits, moving);
  const p = buildPacket(board, { yongKey: 'wealth' });

  assert.equal(p.lines.length, 6, 'six lines');
  assert.deepEqual(p.moving, [3, 4, 5], 'moving lines are reported 1-based');
  assert.ok(p.bian, 'a moving board has a 变卦');
  assert.equal(p.bian.bits.length, 6, '变卦 is six bits');
  for (const l of p.lines) {
    assert.equal(l.transform !== null, l.moving,
      `line ${l.pos}: transform present exactly when the line moves`);
  }
  assert.equal(p.ben.name, '水火既济', 'the packet names the 本卦');
  // Flipping lines 3, 4, 5 of 101010 gives 100100 (from the bottom). The name
  // must be the one the same bits get in section 1, not a hand-typed guess.
  assert.equal(p.bian.bits, '100100', '变卦 bits: lines 3–5 flipped');
  assert.equal(p.bian.name, NAME_OF.get(bitsOf('100100')), 'the 变卦 name comes from its bits');

  // The book's 变卦 six relatives follow the 本卦 palace (动变章). The engine
  // does this, and the packet must not re-derive it from the 变卦 itself.
  assert.ok(p.lines.every((l) => ['parent', 'peer', 'output', 'wealth', 'officer'].includes(l.relative)));

  // 进退 is read from the book's table, not the engine's.
  for (const l of p.lines.filter((x) => x.moving)) {
    assert.equal(l.transform.jinTui, jinTuiOf(l.branch, l.transform.branch),
      `line ${l.pos}: 进退 must come from the book's table`);
  }

  // Tokens: the packet's list is exactly the matcher's list = board features ∪ 关系/状态 tokens.
  const direct = boardFeatures(board, { yongKey: 'wealth' });
  const withFacts = [...new Set([...direct, ...factTokens(p.facts)])].sort();
  assert.deepEqual(p.tokens, withFacts, 'packet.tokens must equal boardFeatures ∪ factTokens');
}

// 4. The packet is data only: JSON-serialisable, no board objects leak through.
{
  const p = buildPacket(boardFor(0b110100, [0]));
  const round = JSON.parse(JSON.stringify(p));
  assert.deepEqual(round, p, 'packet must survive a JSON round trip unchanged');
}

// 5. Input validation.
assert.throws(() => buildPacket(null), /six lines/);
assert.throws(() => buildPacket({ lines: [] }), /six lines/);

console.log('kb-packet: ok — 64 names match 八宫卦吊; 16 进退 pairs match 进神退神章; packet tokens match the matcher');
